<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NADI.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NADI.Core\NADI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Database\Seed\regions.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
